FROM node:20-slim

RUN npm install -g pnpm@9.13.0 && corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --no-frozen-lockfile

COPY . .

RUN pnpm run build

CMD ["pnpm", "test"]
